repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      # - id: no-commit-to-branch
      #   args:
      #     - --branch=main
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      - id: ruff
        args: [ --fix, --verbose ]
      - id: ruff-format
        args: [ --verbose ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
